spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diancan?characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111
mybatis:
    type-aliases-package: cn.bzxy.diancan.pojo
    mapper-locations: classpath:mapper/**.xml
